export const SYSTEM_DEFAULTS = {
  version: "1.0.0",
  updatedAt: "2026-03-21",
  description: "النقطة المرجعية الافتراضية لنظام Mr Code AI — متوافقة مع بيئة الإنتاج",

  runtime: {
    MAX_SEARCHES: 5,
    MAX_ACTIONS_WITHOUT_EDIT: 8,
    MAX_DOM_BLOCKS: 3,
    MAX_LOOPS: 10,
    HISTORY_LIMIT: 20,
  },

  domInspection: {
    sources: ["tool", "search", "user_input", "forced_override"] as const,
    userPatterns: [
      "class[=:]\\s*[\"']([^\"']+)[\"']",
      "\\bclass(?:Name)?\\s*[:=]\\s*[\"']([^\"']+)[\"']",
      "\\bid\\s*[:=]\\s*[\"']([^\"']+)[\"']",
      "(?:div|span|button|section|nav|header|footer|aside|main|ul|li|a|p|h[1-6])\\.[\\w.-]+",
      "المسار:\\s*[^\\n]+",
      "النوع:\\s*<\\w+>",
      "العنصر المحدد",
    ],
    searchCountsAsDOM: true,
    userInputCountsAsDOM: true,
    forcedOverrideAfterBlocks: 3,
  },

  searchStrategy: {
    order: [
      "1. get_page_structure → فحص DOM",
      "2. search_text بالنص المباشر",
      "3. search_text بـ className من DOM",
      "4. search_text في Layout/Sidebar/Header/Nav",
      "5. search_text في i18n",
      "6. read_file فوراً عند وجود match",
      "7. edit_component بعد read_file",
      "8. screenshot_page للتحقق",
    ],
    searchTargets: ["نص مباشر", "t(\"...\")", "label/title/name/placeholder", "children JSX", "className", "data-testid", "aria-label"],
    fallbackFiles: ["Layout.tsx", "Sidebar.tsx", "Header.tsx", "Navigation.tsx", "Nav.tsx"],
    assumeDBOnlyIf: "النص يتغير لكل مستخدم (اسم user/project/API)",
    minSearchesBeforeNotFound: 3,
  },

  emergencyTools: ["run_command", "exec_command"] as const,

  toolRiskConfig: {
    search_text: { risk: "low", category: "search", requiresApproval: false, sandboxed: false },
    list_files: { risk: "low", category: "search", requiresApproval: false, sandboxed: false },
    list_components: { risk: "low", category: "search", requiresApproval: false, sandboxed: false },
    read_file: { risk: "low", category: "files", requiresApproval: false, sandboxed: false },
    view_page_source: { risk: "low", category: "files", requiresApproval: false, sandboxed: false },
    write_file: { risk: "medium", category: "files", requiresApproval: false, sandboxed: false },
    edit_component: { risk: "medium", category: "files", requiresApproval: false, sandboxed: false },
    create_component: { risk: "medium", category: "files", requiresApproval: false, sandboxed: false },
    delete_file: { risk: "high", category: "files", requiresApproval: true, sandboxed: false },
    rename_file: { risk: "medium", category: "files", requiresApproval: false, sandboxed: false },
    db_query: { risk: "medium", category: "database", requiresApproval: false, sandboxed: false },
    db_tables: { risk: "low", category: "database", requiresApproval: false, sandboxed: false },
    run_sql: { risk: "high", category: "database", requiresApproval: true, sandboxed: false },
    run_command: { risk: "critical", category: "system", requiresApproval: true, sandboxed: true },
    exec_command: { risk: "critical", category: "system", requiresApproval: true, sandboxed: true },
    get_env: { risk: "medium", category: "system", requiresApproval: false, sandboxed: false },
    set_env: { risk: "high", category: "system", requiresApproval: true, sandboxed: false },
    system_status: { risk: "low", category: "system", requiresApproval: false, sandboxed: false },
    install_package: { risk: "high", category: "system", requiresApproval: true, sandboxed: false },
    restart_service: { risk: "medium", category: "system", requiresApproval: false, sandboxed: false },
    screenshot_page: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    click_element: { risk: "medium", category: "browser", requiresApproval: false, sandboxed: false },
    type_text: { risk: "medium", category: "browser", requiresApproval: false, sandboxed: false },
    hover_element: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    inspect_styles: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    get_page_structure: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    scroll_page: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    get_console_errors: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    get_network_requests: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    browse_page: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    site_health: { risk: "low", category: "browser", requiresApproval: false, sandboxed: false },
    git_commit: { risk: "medium", category: "deploy", requiresApproval: false, sandboxed: false },
    git_push: { risk: "high", category: "deploy", requiresApproval: true, sandboxed: false },
    trigger_deploy: { risk: "critical", category: "deploy", requiresApproval: true, sandboxed: false },
    deploy_status: { risk: "low", category: "deploy", requiresApproval: false, sandboxed: false },
    github_api: { risk: "medium", category: "deploy", requiresApproval: false, sandboxed: false },
    remote_server_api: { risk: "high", category: "deploy", requiresApproval: true, sandboxed: false },
    rollback_deploy: { risk: "high", category: "deploy", requiresApproval: true, sandboxed: false },
    verify_production: { risk: "medium", category: "deploy", requiresApproval: false, sandboxed: false },
  } as Record<string, { risk: string; category: string; requiresApproval: boolean; sandboxed: boolean }>,

  permToTools: {
    search_text: ["search_text"],
    list_files: ["list_files"],
    list_components: ["list_components"],
    read_file: ["read_file"],
    view_page_source: ["view_page_source"],
    write_file: ["write_file"],
    edit_component: ["edit_component"],
    create_component: ["create_component"],
    delete_file: ["exec_command"],
    rename_file: ["exec_command"],
    db_read: ["db_query", "db_tables"],
    db_write: ["run_sql"],
    db_admin: ["run_sql"],
    db_tables: ["db_tables"],
    run_command: ["run_command"],
    exec_command: ["exec_command"],
    get_env: ["get_env"],
    set_env: ["set_env"],
    system_status: ["system_status"],
    install_package: ["exec_command"],
    restart_service: ["exec_command"],
    screenshot_page: ["screenshot_page"],
    click_element: ["click_element"],
    type_text: ["type_text"],
    hover_element: ["hover_element"],
    inspect_styles: ["inspect_styles"],
    get_page_structure: ["get_page_structure"],
    scroll_page: ["scroll_page"],
    get_console_errors: ["get_console_errors"],
    get_network_requests: ["get_network_requests"],
    browse_page: ["browse_page"],
    site_health: ["site_health"],
    git_push: ["git_push"],
    trigger_deploy: ["trigger_deploy"],
    deploy_status: ["deploy_status"],
    github_api: ["github_api"],
    remote_server_api: ["remote_server_api"],
    rollback_deploy: ["exec_command"],
    manage_users: ["run_sql", "db_query"],
    view_secrets: ["get_env"],
    manage_agents: ["read_file", "write_file", "edit_component"],
    monitor_projects: ["get_project_status", "get_project_logs", "list_project_files"],
    get_project_status: ["get_project_status"],
    get_project_logs: ["get_project_logs"],
    list_project_files: ["list_project_files"],
  } as Record<string, string[]>,

  sqlSafety: {
    dangerousKeywords: ["DROP ", "ALTER ", "TRUNCATE ", "CREATE TABLE", "CREATE INDEX", "GRANT ", "REVOKE ", "DELETE FROM", "INSERT INTO", "UPDATE "],
    readOnlyPrefixes: ["SELECT", "EXPLAIN", "SHOW", "WITH"],
  },

  executionEnginePermissions: [
    "read_file", "search_text", "list_files", "list_components", "view_page_source",
    "get_page_structure", "browse_page", "screenshot_page", "scroll_page", "get_console_errors",
    "write_file", "edit_component", "create_component", "delete_file", "modify_styles",
    "db_read", "db_write", "db_tables", "manage_schema",
    "install_package", "restart_service", "deploy_status",
    "git_push", "trigger_deploy", "rollback_deploy", "verify_production",
    "set_env", "get_env", "system_status", "site_health", "manage_agents", "monitor_projects",
  ],
};

export function getDefaults() {
  return JSON.parse(JSON.stringify(SYSTEM_DEFAULTS));
}
