import type { ProductIntentResult } from "./product-intent-types";
import type { EngineOptions } from "../types/engine-options";

export interface GeneratedSiteFile {
  path: string;
  content: string;
  language?: string;
}

export interface GeneratedSiteBundle {
  files: GeneratedSiteFile[];
  entryFile: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function inferSiteTitle(prompt: string): string {
  const clean = prompt.trim();
  if (!clean) return "AI Generated Website";
  return clean.length > 60 ? `${clean.slice(0, 60).trim()}...` : clean;
}

function inferDirection(prompt: string, intent?: ProductIntentResult): "rtl" | "ltr" {
  if (intent?.rtl) return "rtl";
  return /[\u0600-\u06FF]/.test(prompt) ? "rtl" : "ltr";
}

function inferLang(prompt: string, intent?: ProductIntentResult): "ar" | "en" {
  if (intent?.language) return intent.language;
  return /[\u0600-\u06FF]/.test(prompt) ? "ar" : "en";
}

function buildIntentHeadline(intentType: string, lang: "ar" | "en"): string {
  const mapAr: Record<string, string> = {
    "auction-platform": "منصة مزاد ذكية",
    "marketplace": "منصة سوق إلكتروني",
    "dashboard": "لوحة تحكم تحليلية",
    "admin-panel": "لوحة إدارة متقدمة",
    "saas-app": "منصة خدمة رقمية",
    "crud-app": "تطبيق إدارة بيانات",
    "content-site": "موقع محتوى احترافي",
    "portfolio": "معرض أعمال احترافي",
    "landing-page": "صفحة هبوط احترافية",
    "business-website": "موقع أعمال احترافي",
    "general-web-app": "تطبيق ويب ذكي",
  };

  const mapEn: Record<string, string> = {
    "auction-platform": "Smart Auction Platform",
    "marketplace": "Marketplace Platform",
    "dashboard": "Analytics Dashboard",
    "admin-panel": "Advanced Admin Panel",
    "saas-app": "SaaS Platform",
    "crud-app": "Data Management App",
    "content-site": "Professional Content Website",
    "portfolio": "Professional Portfolio",
    "landing-page": "High-Converting Landing Page",
    "business-website": "Professional Business Website",
    "general-web-app": "Smart Web App",
  };

  return lang === "ar" ? mapAr[intentType] || "موقع تم إنشاؤه بالذكاء الاصطناعي" : mapEn[intentType] || "Website generated by AI";
}

function buildFeatures(intentType: string, lang: "ar" | "en"): string[] {
  const byIntentAr: Record<string, string[]> = {
    "auction-platform": ["بطاقات مزادات", "حالات المزايدة", "عد تنازلي", "عرض أسعار واضح"],
    "marketplace": ["قوائم منتجات", "بطاقات عرض", "بحث وتصفية", "واجهة بيع وشراء"],
    "dashboard": ["بطاقات إحصائية", "مؤشرات أداء", "جداول", "فلاتر"],
    "admin-panel": ["إدارة المحتوى", "صلاحيات", "جداول بيانات", "إجراءات سريعة"],
    "saas-app": ["واجهة خدمة", "مزايا المنتج", "دعوة للاشتراك", "هيكل قابل للتوسع"],
    "crud-app": ["نماذج إدخال", "جداول بيانات", "عمليات إدارة", "تنظيم واضح"],
    "content-site": ["مقالات مميزة", "أقسام محتوى", "هيكل قراءة واضح", "عرض منظم"],
    "portfolio": ["عرض مشاريع", "سيرة مختصرة", "نقاط تميز", "دعوة للتواصل"],
    "landing-page": ["رسالة قوية", "قسم مزايا", "دعوة لاتخاذ إجراء", "بنية تحويل"],
    "business-website": ["تعريف بالخدمة", "مزايا الأعمال", "دعوة للتواصل", "تصميم احترافي"],
    "general-web-app": ["تصميم واضح", "أقسام رئيسية", "قابلية التوسع", "معاينة جاهزة"],
  };

  const byIntentEn: Record<string, string[]> = {
    "auction-platform": ["Auction cards", "Bid states", "Countdown", "Clear pricing UI"],
    "marketplace": ["Listings", "Product cards", "Search and filters", "Buy/sell flow"],
    "dashboard": ["Stat cards", "KPIs", "Tables", "Filters"],
    "admin-panel": ["Content control", "Roles", "Tables", "Quick actions"],
    "saas-app": ["Product UI", "Core benefits", "Signup CTA", "Scalable structure"],
    "crud-app": ["Input forms", "Data tables", "Management actions", "Clear workflow"],
    "content-site": ["Featured articles", "Content sections", "Readable layout", "Organized display"],
    "portfolio": ["Project showcase", "Short bio", "Highlights", "Contact CTA"],
    "landing-page": ["Strong hero", "Feature section", "Primary CTA", "Conversion structure"],
    "business-website": ["Service overview", "Business value", "Contact CTA", "Professional layout"],
    "general-web-app": ["Clean design", "Core sections", "Scalable structure", "Ready preview"],
  };

  return lang === "ar"
    ? byIntentAr[intentType] || byIntentAr["general-web-app"]
    : byIntentEn[intentType] || byIntentEn["general-web-app"];
}

export class DefaultSiteGenerator {
  static build(prompt: string, intent?: ProductIntentResult, options?: EngineOptions): GeneratedSiteBundle {
    if (options?.tech && options.tech !== "html") {
      return DefaultSiteGenerator.buildWithTech(prompt, intent, options);
    }

    const lang = inferLang(prompt, intent);
    const dir = inferDirection(prompt, intent);
    const title = inferSiteTitle(prompt);
    const intentType = intent?.type || "general-web-app";
    const headline = buildIntentHeadline(intentType, lang);
    const features = buildFeatures(intentType, lang);

    const techBadge = options?.tech ? ` • ${options.tech}` : "";
    const outputBadge = options?.output ? ` • ${options.output}` : "";

    const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <div class="site-shell">
    <header class="hero">
      <div class="badge">${lang === "ar" ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)}${techBadge}${outputBadge}</div>
      <h1>${headline}</h1>
      <p class="subheadline">${
        lang === "ar"
          ? `تم إنشاء هذا النموذج الأولي بناءً على طلبك مع توجيه نوع المنتج: ${escapeHtml(intentType)}`
          : `This prototype was generated based on your request with product intent: ${escapeHtml(intentType)}`
      }</p>

      <div class="hero-actions">
        <button id="primary-action" class="btn btn-primary" data-testid="button-primary-action">
          ${lang === "ar" ? "ابدأ الآن" : "Get Started"}
        </button>
        <button id="secondary-action" class="btn btn-secondary" data-testid="button-secondary-action">
          ${lang === "ar" ? "اعرف المزيد" : "Learn More"}
        </button>
      </div>
    </header>

    <main class="content">
      <section class="card">
        <h2>${lang === "ar" ? "المزايا الرئيسية" : "Key Features"}</h2>
        <div class="feature-grid">
          ${features
            .map(
              (item) => `
            <article class="feature-item">
              <h3>${escapeHtml(item)}</h3>
              <p>${lang === "ar" ? "تم تخصيص هذه النقطة بحسب نوع المنتج المكتشف." : "This item was adapted to the detected product intent."}</p>
            </article>
          `
            )
            .join("")}
        </div>
      </section>
    </main>
  </div>

  <script src="./script.js"></script>
</body>
</html>`;

    const css = `:root {
  color-scheme: dark;
  --bg: #0b1220;
  --panel: #121a2b;
  --text: #f5f7fb;
  --muted: #a8b3c7;
  --line: rgba(255,255,255,0.08);
  --primary: #5aa9ff;
  --primary-2: #2f7fe0;
}
* { box-sizing: border-box; }
html, body { margin:0; padding:0; background:#0b1220; color:var(--text); font-family:Inter,system-ui,sans-serif; }
.site-shell { width:min(1100px, calc(100% - 32px)); margin:0 auto; padding:32px 0 56px; }
.hero,.card { background:#121a2b; border:1px solid var(--line); border-radius:22px; }
.hero { padding:40px 28px; margin-bottom:20px; }
.badge { display:inline-flex; padding:8px 14px; border-radius:999px; background:rgba(90,169,255,0.12); color:#cfe5ff; margin-bottom:18px; }
h1 { font-size:clamp(30px,5vw,56px); line-height:1.05; margin:0 0 14px; }
.subheadline { color:var(--muted); font-size:18px; line-height:1.7; max-width:800px; }
.hero-actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:22px; }
.btn { border:none; border-radius:14px; padding:14px 18px; font-size:15px; font-weight:600; cursor:pointer; }
.btn-primary { background:linear-gradient(180deg, var(--primary), var(--primary-2)); color:white; }
.btn-secondary { background:rgba(255,255,255,0.06); color:white; border:1px solid var(--line); }
.content { display:grid; gap:20px; }
.card { padding:24px; }
.feature-grid { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:16px; }
.feature-item { background:#182338; border:1px solid var(--line); border-radius:18px; padding:18px; }
@media (max-width:720px) {
  .site-shell { width:min(100% - 20px, 1100px); padding-top:20px; }
  .feature-grid { grid-template-columns:1fr; }
}`;

    const js = `document.getElementById("primary-action")?.addEventListener("click", () => {
  alert(${JSON.stringify(lang === "ar" ? "تم تنفيذ الإجراء الرئيسي." : "Primary action executed.")});
});
document.getElementById("secondary-action")?.addEventListener("click", () => {
  alert(${JSON.stringify(lang === "ar" ? "تم تنفيذ الإجراء الثانوي." : "Secondary action executed.")});
});`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: html, language: "html" },
        { path: "style.css", content: css, language: "css" },
        { path: "script.js", content: js, language: "javascript" },
      ],
    };
  }

  private static buildWithTech(prompt: string, intent?: ProductIntentResult, options?: EngineOptions): GeneratedSiteBundle {
    const lang = inferLang(prompt, intent);
    const dir = inferDirection(prompt, intent);
    const title = inferSiteTitle(prompt);
    const intentType = intent?.type || "general-web-app";
    const headline = buildIntentHeadline(intentType, lang);
    const features = buildFeatures(intentType, lang);
    const tech = options?.tech || "html";

    switch (tech) {
      case "react":
      case "next":
        return DefaultSiteGenerator.buildReact(lang, dir, title, intentType, headline, features, options);
      case "vue":
      case "nuxt":
        return DefaultSiteGenerator.buildVue(lang, dir, title, intentType, headline, features, options);
      case "tailwind":
        return DefaultSiteGenerator.buildTailwind(lang, dir, title, intentType, headline, features, options);
      case "bootstrap":
        return DefaultSiteGenerator.buildBootstrap(lang, dir, title, intentType, headline, features, options);
      default:
        return DefaultSiteGenerator.buildGenericFramework(lang, dir, title, intentType, headline, features, tech, options);
    }
  }

  private static buildReact(lang: string, dir: string, title: string, intentType: string, headline: string, features: string[], options?: EngineOptions): GeneratedSiteBundle {
    const isAr = lang === "ar";

    const appTsx = `import { useState } from 'react';
import './App.css';

function FeatureCard({ title, description }: { title: string; description: string }) {
  return (
    <article className="feature-item" data-testid="card-feature">
      <h3>{title}</h3>
      <p>{description}</p>
    </article>
  );
}

export default function App() {
  const [clicked, setClicked] = useState(false);

  return (
    <div className="site-shell" dir="${dir}">
      <header className="hero">
        <div className="badge">${isAr ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)} • React</div>
        <h1>${headline}</h1>
        <p className="subheadline">
          ${isAr ? `تم إنشاء هذا بواسطة React مع توجيه: ${escapeHtml(intentType)}` : `Built with React • Intent: ${escapeHtml(intentType)}`}
        </p>
        <div className="hero-actions">
          <button data-testid="button-primary" className="btn btn-primary" onClick={() => setClicked(true)}>
            ${isAr ? "ابدأ الآن" : "Get Started"}
          </button>
          <button data-testid="button-secondary" className="btn btn-secondary" onClick={() => alert('${isAr ? "اعرف المزيد" : "Learn More"}')}>
            ${isAr ? "اعرف المزيد" : "Learn More"}
          </button>
        </div>
        {clicked && <p className="status-msg" data-testid="text-status">${isAr ? "تم تفعيل الحدث!" : "Action triggered!"}</p>}
      </header>

      <main className="content">
        <section className="card">
          <h2>${isAr ? "المزايا الرئيسية" : "Key Features"}</h2>
          <div className="feature-grid">
            {${JSON.stringify(features)}.map((f, i) => (
              <FeatureCard key={i} title={f} description="${isAr ? "مخصص حسب نوع المنتج" : "Adapted to product intent"}" />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
`;

    const indexHtml = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="./main.tsx"></script>
</body>
</html>`;

    const mainTsx = `import { createRoot } from 'react-dom/client';
import App from './App';
import './App.css';

createRoot(document.getElementById('root')!).render(<App />);
`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: indexHtml, language: "html" },
        { path: "App.tsx", content: appTsx, language: "tsx" },
        { path: "main.tsx", content: mainTsx, language: "tsx" },
        { path: "App.css", content: DefaultSiteGenerator.getBaseCSS(), language: "css" },
      ],
    };
  }

  private static buildVue(lang: string, dir: string, title: string, intentType: string, headline: string, features: string[], options?: EngineOptions): GeneratedSiteBundle {
    const isAr = lang === "ar";

    const appVue = `<script setup lang="ts">
import { ref } from 'vue';

const clicked = ref(false);
const features = ${JSON.stringify(features)};
</script>

<template>
  <div class="site-shell" dir="${dir}">
    <header class="hero">
      <div class="badge">${isAr ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)} • Vue</div>
      <h1>${headline}</h1>
      <p class="subheadline">
        ${isAr ? `تم إنشاء هذا بواسطة Vue مع توجيه: ${escapeHtml(intentType)}` : `Built with Vue.js • Intent: ${escapeHtml(intentType)}`}
      </p>
      <div class="hero-actions">
        <button data-testid="button-primary" class="btn btn-primary" @click="clicked = true">
          ${isAr ? "ابدأ الآن" : "Get Started"}
        </button>
        <button data-testid="button-secondary" class="btn btn-secondary" @click="alert('${isAr ? "اعرف المزيد" : "Learn More"}')">
          ${isAr ? "اعرف المزيد" : "Learn More"}
        </button>
      </div>
      <p v-if="clicked" class="status-msg" data-testid="text-status">${isAr ? "تم تفعيل الحدث!" : "Action triggered!"}</p>
    </header>

    <main class="content">
      <section class="card">
        <h2>${isAr ? "المزايا الرئيسية" : "Key Features"}</h2>
        <div class="feature-grid">
          <article v-for="(f, i) in features" :key="i" class="feature-item" data-testid="card-feature">
            <h3>{{ f }}</h3>
            <p>${isAr ? "مخصص حسب نوع المنتج" : "Adapted to product intent"}</p>
          </article>
        </div>
      </section>
    </main>
  </div>
</template>

<style src="./style.css"></style>
`;

    const indexHtml = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
</head>
<body>
  <div id="app"></div>
  <script type="module" src="./main.ts"></script>
</body>
</html>`;

    const mainTs = `import { createApp } from 'vue';
import App from './App.vue';

createApp(App).mount('#app');
`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: indexHtml, language: "html" },
        { path: "App.vue", content: appVue, language: "vue" },
        { path: "main.ts", content: mainTs, language: "typescript" },
        { path: "style.css", content: DefaultSiteGenerator.getBaseCSS(), language: "css" },
      ],
    };
  }

  private static buildTailwind(lang: string, dir: string, title: string, intentType: string, headline: string, features: string[], options?: EngineOptions): GeneratedSiteBundle {
    const isAr = lang === "ar";

    const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-950 text-white font-sans min-h-screen">
  <div class="max-w-5xl mx-auto px-4 py-8">
    <header class="bg-gray-900 border border-gray-800 rounded-2xl p-8 mb-6">
      <span class="inline-block px-3 py-1 rounded-full bg-blue-500/10 text-blue-300 text-sm mb-4" data-testid="text-badge">
        ${isAr ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)} • Tailwind
      </span>
      <h1 class="text-4xl md:text-5xl font-bold mb-3" data-testid="text-headline">${headline}</h1>
      <p class="text-gray-400 text-lg max-w-2xl">
        ${isAr ? `تم إنشاء هذا بواسطة Tailwind CSS مع توجيه: ${escapeHtml(intentType)}` : `Built with Tailwind CSS • Intent: ${escapeHtml(intentType)}`}
      </p>
      <div class="flex flex-wrap gap-3 mt-6">
        <button data-testid="button-primary" class="px-6 py-3 bg-gradient-to-b from-blue-500 to-blue-600 rounded-xl font-semibold hover:from-blue-400 hover:to-blue-500 transition">${isAr ? "ابدأ الآن" : "Get Started"}</button>
        <button data-testid="button-secondary" class="px-6 py-3 bg-white/5 border border-gray-700 rounded-xl font-semibold hover:bg-white/10 transition">${isAr ? "اعرف المزيد" : "Learn More"}</button>
      </div>
    </header>

    <section class="bg-gray-900 border border-gray-800 rounded-2xl p-6">
      <h2 class="text-2xl font-bold mb-4">${isAr ? "المزايا الرئيسية" : "Key Features"}</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        ${features.map(f => `
        <article class="bg-gray-800/50 border border-gray-700 rounded-xl p-4" data-testid="card-feature">
          <h3 class="font-semibold mb-1">${escapeHtml(f)}</h3>
          <p class="text-gray-400 text-sm">${isAr ? "مخصص حسب نوع المنتج" : "Adapted to product intent"}</p>
        </article>`).join("")}
      </div>
    </section>
  </div>

  <script src="./script.js"></script>
</body>
</html>`;

    const js = `document.querySelector('[data-testid="button-primary"]')?.addEventListener("click", () => {
  alert(${JSON.stringify(isAr ? "تم تنفيذ الإجراء الرئيسي." : "Primary action executed.")});
});`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: html, language: "html" },
        { path: "script.js", content: js, language: "javascript" },
      ],
    };
  }

  private static buildBootstrap(lang: string, dir: string, title: string, intentType: string, headline: string, features: string[], options?: EngineOptions): GeneratedSiteBundle {
    const isAr = lang === "ar";

    const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="./style.css" />
</head>
<body class="bg-dark text-white">
  <div class="container py-5">
    <header class="bg-dark border border-secondary rounded-4 p-5 mb-4">
      <span class="badge bg-primary bg-opacity-25 text-info mb-3" data-testid="text-badge">
        ${isAr ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)} • Bootstrap
      </span>
      <h1 class="display-4 fw-bold" data-testid="text-headline">${headline}</h1>
      <p class="text-secondary fs-5">
        ${isAr ? `تم إنشاء هذا بواسطة Bootstrap مع توجيه: ${escapeHtml(intentType)}` : `Built with Bootstrap • Intent: ${escapeHtml(intentType)}`}
      </p>
      <div class="d-flex flex-wrap gap-2 mt-4">
        <button data-testid="button-primary" class="btn btn-primary btn-lg">${isAr ? "ابدأ الآن" : "Get Started"}</button>
        <button data-testid="button-secondary" class="btn btn-outline-light btn-lg">${isAr ? "اعرف المزيد" : "Learn More"}</button>
      </div>
    </header>

    <section class="bg-dark border border-secondary rounded-4 p-4">
      <h2 class="h3 fw-bold mb-3">${isAr ? "المزايا الرئيسية" : "Key Features"}</h2>
      <div class="row g-3">
        ${features.map(f => `
        <div class="col-md-6">
          <div class="card bg-dark border-secondary" data-testid="card-feature">
            <div class="card-body">
              <h5 class="card-title">${escapeHtml(f)}</h5>
              <p class="card-text text-secondary">${isAr ? "مخصص حسب نوع المنتج" : "Adapted to product intent"}</p>
            </div>
          </div>
        </div>`).join("")}
      </div>
    </section>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="./script.js"></script>
</body>
</html>`;

    const css = `body { min-height: 100vh; }
.rounded-4 { border-radius: 1.25rem !important; }`;

    const js = `document.querySelector('[data-testid="button-primary"]')?.addEventListener("click", () => {
  alert(${JSON.stringify(isAr ? "تم تنفيذ الإجراء الرئيسي." : "Primary action executed.")});
});`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: html, language: "html" },
        { path: "style.css", content: css, language: "css" },
        { path: "script.js", content: js, language: "javascript" },
      ],
    };
  }

  private static buildGenericFramework(lang: string, dir: string, title: string, intentType: string, headline: string, features: string[], tech: string, options?: EngineOptions): GeneratedSiteBundle {
    const isAr = lang === "ar";

    const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <div class="site-shell">
    <header class="hero">
      <div class="badge">${isAr ? "نسخة أولية" : "Prototype"} • ${escapeHtml(intentType)} • ${escapeHtml(tech)}</div>
      <h1>${headline}</h1>
      <p class="subheadline">
        ${isAr ? `تم إنشاء هذا للتقنية: ${escapeHtml(tech)} مع توجيه: ${escapeHtml(intentType)}` : `Built for ${escapeHtml(tech)} • Intent: ${escapeHtml(intentType)}`}
      </p>
      <div class="hero-actions">
        <button id="primary-action" class="btn btn-primary" data-testid="button-primary-action">
          ${isAr ? "ابدأ الآن" : "Get Started"}
        </button>
      </div>
    </header>

    <main class="content">
      <section class="card">
        <h2>${isAr ? "المزايا الرئيسية" : "Key Features"}</h2>
        <div class="feature-grid">
          ${features.map(item => `
            <article class="feature-item" data-testid="card-feature">
              <h3>${escapeHtml(item)}</h3>
              <p>${isAr ? "مخصص حسب نوع المنتج" : "Adapted to product intent"}</p>
            </article>
          `).join("")}
        </div>
      </section>

      <section class="card">
        <h2>${isAr ? "ملاحظات التقنية" : "Tech Notes"}</h2>
        <p class="subheadline">${isAr ? `هذا النموذج مُعد للاستخدام مع ${escapeHtml(tech)}. يمكنك البدء بتطويره مباشرة.` : `This prototype is prepared for ${escapeHtml(tech)}. You can start developing immediately.`}</p>
      </section>
    </main>
  </div>

  <script src="./script.js"></script>
</body>
</html>`;

    const js = `document.getElementById("primary-action")?.addEventListener("click", () => {
  alert(${JSON.stringify(isAr ? "تم تنفيذ الإجراء." : "Action executed.")});
});
console.log("Tech stack: ${tech}");`;

    return {
      entryFile: "index.html",
      files: [
        { path: "index.html", content: html, language: "html" },
        { path: "style.css", content: DefaultSiteGenerator.getBaseCSS(), language: "css" },
        { path: "script.js", content: js, language: "javascript" },
      ],
    };
  }

  private static getBaseCSS(): string {
    return `:root {
  color-scheme: dark;
  --bg: #0b1220;
  --panel: #121a2b;
  --text: #f5f7fb;
  --muted: #a8b3c7;
  --line: rgba(255,255,255,0.08);
  --primary: #5aa9ff;
  --primary-2: #2f7fe0;
}
* { box-sizing: border-box; }
html, body { margin:0; padding:0; background:#0b1220; color:var(--text); font-family:Inter,system-ui,sans-serif; }
.site-shell { width:min(1100px, calc(100% - 32px)); margin:0 auto; padding:32px 0 56px; }
.hero,.card { background:#121a2b; border:1px solid var(--line); border-radius:22px; }
.hero { padding:40px 28px; margin-bottom:20px; }
.badge { display:inline-flex; padding:8px 14px; border-radius:999px; background:rgba(90,169,255,0.12); color:#cfe5ff; margin-bottom:18px; }
h1 { font-size:clamp(30px,5vw,56px); line-height:1.05; margin:0 0 14px; }
.subheadline { color:var(--muted); font-size:18px; line-height:1.7; max-width:800px; }
.hero-actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:22px; }
.btn { border:none; border-radius:14px; padding:14px 18px; font-size:15px; font-weight:600; cursor:pointer; }
.btn-primary { background:linear-gradient(180deg, var(--primary), var(--primary-2)); color:white; }
.btn-secondary { background:rgba(255,255,255,0.06); color:white; border:1px solid var(--line); }
.content { display:grid; gap:20px; }
.card { padding:24px; }
.feature-grid { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:16px; }
.feature-item { background:#182338; border:1px solid var(--line); border-radius:18px; padding:18px; }
.status-msg { color:#5aa9ff; margin-top:12px; font-weight:500; }
@media (max-width:720px) {
  .site-shell { width:min(100% - 20px, 1100px); padding-top:20px; }
  .feature-grid { grid-template-columns:1fr; }
}`;
  }
}
